/**
 * Side-by-side: a representative DTO written with the class-validator util decorators VS the same shape written as
 * an arktype schema using the util-validators in this directory.
 *
 * The `Before` class uses every category of util-decorator we ported:
 *
 * - GraphQL field decorators bundling class-validator + @Field.
 * - The 4-way nullability matrix (Required / Optional / StrictNullable / StrictOptional)
 * - Custom validators (timezone, url-or-localhost, currency, phone, int32)
 * - Cross-field XOR.
 * - Array distinct-by.
 * - String trim transform.
 *
 * The `After` schema is the arktype rewrite. The GraphQL `@InputType` is generated by `createArkInputType`
 * (already in `src/arktype/graphql-arktype/`), so the only thing we author is the schema.
 */

// =============================================================================
// BEFORE — class-validator + class-transformer + @nestjs/graphql
// =============================================================================
//
// Import { InputType } from '@nestjs/graphql';
// Import { Type } from 'class-transformer';
// Import { Validate } from 'class-validator';
// Import {
//   ArrayDistinct,
//   GraphQLOptionalNestedObjectField,
//   GraphQLRequiredEnumField,
//   GraphQLRequiredIdField,
//   GraphQLRequiredPositiveIntField,
//   GraphQLRequiredStringField,
//   GraphQLStrictNullableStringField,
//   GraphQLStrictOptionalStringField,
//   IsCurrencyValue,
//   IsPossiblePhoneNumber,
//   IsRecordStringPositiveInteger,
//   IsTimezone,
//   IsUrlOrLocalhost,
//   TrimString,
//   XorConstraint,
// } from '../util-decorators';
//
// Enum FulfilmentMethod { PICKUP = 'PICKUP', DELIVERY = 'DELIVERY' }
//
// @InputType()
// Class TagInput {
//   @GraphQLRequiredIdField({ name: 'id', description: 'Tag id' })
//   Id!: string;
//
//   @GraphQLRequiredStringField({ name: 'label', description: 'Tag label' })
//   @TrimString()
//   Label!: string;
// }
//
// @InputType()
// Class CheckoutInput {
//   @GraphQLRequiredIdField({ name: 'cartId', description: 'Cart id' })
//   CartId!: string;
//
//   @GraphQLRequiredEnumField(FulfilmentMethod, {
//     Name: 'method',
//     Description: 'Pickup or delivery',
//   })
//   Method!: FulfilmentMethod;
//
//   @GraphQLRequiredPositiveIntField({ name: 'totalCents', description: 'Total' })
//   TotalCents!: number;
//
//   @GraphQLRequiredStringField({ name: 'currency', description: 'ISO 4217' })
//   @IsCurrencyValue()
//   CurrencyAmount!: string;
//
//   @GraphQLRequiredStringField({ name: 'timezone', description: 'IANA tz' })
//   @IsTimezone()
//   Timezone!: string;
//
//   @GraphQLStrictOptionalStringField({ name: 'callbackUrl', description: 'webhook' })
//   @IsUrlOrLocalhost()
//   CallbackUrl?: string;
//
//   @GraphQLStrictNullableStringField({ name: 'phone', description: 'phone' })
//   @IsPossiblePhoneNumber()
//   Phone!: string | null;
//
//   @ArrayDistinct('id')
//   @ValidateNested({ each: true })
//   @Type(() => TagInput)
//   Tags!: TagInput[];
//
//   @IsRecordStringPositiveInteger()
//   SelectedAddOns!: Record<string, number>;
//
//   // XOR pair: exactly one of these two is set
//   @XorConstraint('giftMessage')
//   CouponCode?: string;
//
//   @XorConstraint('couponCode')
//   GiftMessage?: string;
// }

// =============================================================================
// AFTER — arktype + util-validators (this directory)
// =============================================================================

import { type } from 'arktype';
import { createArkInputType } from '../arktype/graphql-arktype';
import {
    CurrencyValue,
    PositiveInt,
    PossiblePhoneNumber,
    RecordOfPositiveInt,
    Timezone,
    TrimmedString,
    UrlOrLocalhost,
    arrayDistinctBy,
    xorOf,
} from './';

// Plain string-literal enums — arktype handles them natively, no
// `registerEnumType` needed unless you want a real GraphQL enum type
// (in which case use `registerArkEnum` from graphql-arktype).
const FulfilmentMethod = type("'PICKUP' | 'DELIVERY'");

const TagSchema = type({
    id: 'string.uuid',
    label: TrimmedString,
});

const CheckoutSchema = type({
    cartId: 'string.uuid',
    method: FulfilmentMethod,
    totalCents: PositiveInt,
    currencyAmount: CurrencyValue,
    timezone: Timezone,
    // Strict-optional: undefined OK, null forbidden
    'callbackUrl?': UrlOrLocalhost,
    // Strict-nullable: null OK, undefined forbidden
    phone: PossiblePhoneNumber.or('null'),
    tags: arrayDistinctBy(TagSchema, 'id'),
    selectedAddOns: RecordOfPositiveInt,
    // XOR pair
    'couponCode?': 'string > 0',
    'giftMessage?': 'string > 0',
}).narrow(xorOf('couponCode', 'giftMessage'));

// Generates the `@InputType` + `@Field()` decorators automatically from the
// JSON-schema form of `CheckoutSchema`. Nested types (`tags` → TagInput) are
// Auto-resolved via the registry — see `graphql-arktype/core/json-schema-to-gql.ts`.
export const TagInput = createArkInputType(TagSchema, { name: 'TagInput' });

export const CheckoutInput = createArkInputType(CheckoutSchema, {
    fields: {
        tags: () => [TagInput],
    },
    name: 'CheckoutInput',
});

export type CheckoutShape = typeof CheckoutSchema.infer;
